# Generated by Django 4.2.11 on 2024-05-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mockquiz_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockquiz_item',
            old_name='exam',
            new_name='quiz',
        ),
    ]
